version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: fasta_chatting
      POSTGRES_DB: fasta_chatting_production
    ports:
      - "5432:5432"
  web:
    build: .
    volumes:
      - .:/myapp
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: fasta_chatting
      POSTGRES_DB: fasta_chatting_production
      POSTGRESS_HOST: db
      POSTGRESS_PORT: '5432'
    ports:
      - "3000:3000"
    depends_on:
      - db
  redis:
   image: "redis:4.0-alpine"
   command: redis-server
   ports:
      - "6379:6379"
   volumes:
      - redis:/data
volumes:
 db:
 redis:
